<a href="https://colab.research.google.com/github/tiagoIva9Lavinas/Faculdade-IA/blob/main/NumPy%2C_SciPy%2C_Pandas%2C_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NumPy**

1. Crie um array unidimensional de 50 elementos contendo números inteiros
aleatórios entre 10 e 100.

In [ ]:
import numpy as np

array = np.random.randint(10,101,50)

print(array)

[33 96 89 62 93 75 86 46 66 48 98 50 65 73 42 48 76 42 11 62 35 68 93 20
 34 82 45 90 16 57 10 49 58 41 38 76 54 32 19 66 33 37 58 42 24 15 74 32
 44 81]


2.	Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

In [ ]:
import numpy as np

array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

print("Array: \n", array)

print("\nUltima linha: \n", array[3])

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Ultima linha: 
 [13 14 15 16]


3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
à 10ª posição por 1.

In [ ]:
import numpy as np

array = np.zeros(15)

array[4:10] = 1

print("Array com substituicao:", array)

Array com substituicao: [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

In [ ]:
import numpy as np

array = np.random.randint(0,100,100)

mediana = np.median(array)

valores, contagem = np.unique(array, return_counts=True)

moda = valores[np.argmax(contagem)]

print("Mediana:", mediana)
print("Moda:", moda, "Repetições:", np.max(contagem))

Mediana: 55.0
Moda: 64 Repetições: 4


5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua
todos os valores múltiplos de 3 por -3.

In [ ]:
import numpy as np

array = np.random.randint(1,101,20)

for n in range(len(array)):
  if n % 3 == 0:
    array[n]=-3
print(array)

[ -3  39 100  -3 100  17  -3  96  42  -3  10  12  -3  27  67  -3  21  67
  -3  43]


6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma
de cada coluna.

In [ ]:
import numpy as np

array = np.random.rand(5 , 5)

coluna_0 = sum(array[: , 0])
coluna_1 = sum(array[: , 1])
coluna_2 = sum(array[: , 2])
coluna_3 = sum(array[: , 3])
coluna_4 = sum(array[: , 4])

print("Soma da Coluna 0:", coluna_0)
print("Soma da Coluna 1:", coluna_1)
print("Soma da Coluna 2:", coluna_2)
print("Soma da Coluna 3:", coluna_3)
print("Soma da Coluna 4:", coluna_4)

Soma da Coluna 0: 2.8521384034151964
Soma da Coluna 1: 1.4680944159428795
Soma da Coluna 2: 3.423025008101198
Soma da Coluna 3: 1.8837690050740012
Soma da Coluna 4: 3.3308174991502026


7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [ ]:
import numpy as np

array1 = np.random.randint(1,100,30)
array2 = np.random.randint(1,100,30)

correlacao = np.corrcoef(a,b)[0,1]

print("Correlacao das arrays:", correlacao)

8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus
elementos ao quadrado.

In [ ]:
import numpy as np

array = np.random.randint(1,10,(3,3))
array_q = np.square(array)
print("Elementos ao quadrado:", array_q)



Elementos ao quadrado: [[16  1 64]
 [81  9  9]
 [81 36 64]]


9. Crie um array com 10 números aleatórios e normalize seus valores entre 0
e 1.

In [ ]:
import numpy as np

array = np.random.randint(1,100,10)
array = np.random.rand(10)

print(array)

[0.06447778 0.67832891 0.7871933  0.32834405 0.90871983 0.36072199
 0.13801796 0.64704995 0.16920527 0.04347449]


10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.

In [ ]:
import numpy as np

array = np.eye(6)

contagem = 1
for n in range(6):
  array[n,n] = n+1

print(array)

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


11. Gere um array de 100 números inteiros e encontre o valor que mais se
repete no array.

In [ ]:
import numpy as np

array = np.random.randint(0,100,100)

valores, contagem = np.unique(array, return_counts=True)

moda = valores[np.argmax(contagem)]

print("Valor que mais se repete é:", moda)

Valor que mais se repete é: 50


12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [ ]:
import numpy as np

array = np.random.randint(1,10,(4,4))

contagem = 1
for n in range(4):
  array[n,n] = 4

print(array)

[[4 5 8 2]
 [9 4 4 4]
 [2 2 4 6]
 [3 6 1 4]]


13. Crie um array contendo os 10 primeiros números pares e calcule sua soma
cumulativa.

In [ ]:
import numpy as np

array = np.array([2,4,6,8,10,12,14,16,18,20])

soma = np.sum(array)
soma_c = np.cumsum(array)

print("Soma:", soma)
print("Soma cumulativa:", soma_c)

Soma: 110
Soma cumulativa: [  2   6  12  20  30  42  56  72  90 110]


14. Calcule a diferença entre dois arrays de números aleatórios de mesmo
comprimento e encontre a média das diferenças.

In [ ]:
import numpy as np

array_1 = np.random.rand(10)
array_2 = np.random.rand(10)

diferenca = array_1 - array_2

media = np.mean(diferenca)

print("Média:", media)

15. Gere um array contendo 20 números e substitua todos os valores maiores
que 50 por 50.

In [ ]:
import numpy as np

array = np.random.randint(1,100,20)

for n in range(len(array)):
  if array[n] > 50:
    array[n] = 50

print(array)

[50 27 50 50 50  6 31  5 23 15 50 23  3 50 50 50 21 50  2 42]


16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.

In [12]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

array_3x4 = np.reshape(array, (3,4))

print(array_3x4)

[[15 18 21 24]]
